# 1. Exploratory data analysis

# Load libraries needed for RNA-seq analysis
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("DESeq2")

library(DESeq2)
library(ggplot2)
library(pheatmap)


# Import count matrix generated by featureCounts
counts <- read.table(
  "counts_clean.txt",
  header = TRUE,
  row.names = 1,
  check.names = FALSE
)

# Remove full file paths from column names so that only sample IDs remain
colnames(counts) <- sub(".*/(SRR[0-9]+)\\.sorted\\.bam", "\\1", colnames(counts))

# Inspect dimensions and first few rows
colnames(counts)
dim(counts)
head(counts[, 1:6])


# Define sample metadata describing genotype and infection status
sample_info <- data.frame(
  row.names = colnames(counts),
  genotype = c(
    "WT","WT","WT","WT","WT",
    "DKO","DKO","DKO","DKO",
    "WT","WT","WT",
    "DKO","DKO","DKO"
  ),
  infection = c(
    "Case","Case","Case","Case","Case",
    "Case","Case","Case","Case",
    "Control","Control","Control",
    "Control","Control","Control"
  )
)

# Check that sample order matches between counts and metadata
all(rownames(sample_info) == colnames(counts))


# Create DESeq2 dataset with a design accounting for genotype and infection
dds <- DESeqDataSetFromMatrix(
  countData = counts,
  colData = sample_info,
  design = ~ genotype + infection
)

# Run normalization and model fitting
dds <- DESeq(dds)
resultsNames(dds)


# Apply variance-stabilizing transformation for visualization
vsd <- vst(dds, blind = TRUE)

# PCA plot to explore global expression patterns
p <- plotPCA(vsd, intgroup = c("genotype", "infection"))
print(p)

# Save PCA plot
ggsave("PCA_plot.png", p, width = 6, height = 5)

# Extract PC1 and PC2 values for each sample
pca_data <- plotPCA(
  vsd,
  intgroup = c("genotype", "infection"),
  returnData = TRUE
)

pc1_table <- pca_data[, c("name", "PC1", "PC2")]
print(pc1_table)


# Optional deeper PCA inspection using prcomp
# This allows investigation of gene loadings
pca <- prcomp(t(assay(vsd)))

# Loadings indicate how strongly each gene contributes to each PC
loadings <- pca$rotation

# Identify genes with strongest contributions to PC1
top_PC1_genes <- head(
  sort(abs(loadings[, 1]), decreasing = TRUE),
  20
)

top_PC1_genes


# 2. Differential expression analysis

# Genotype comparison (DKO vs WT), ignoring infection
res_genotype <- results(dds, contrast = c("genotype", "DKO", "WT"))
summary(res_genotype)

# Infection comparison (Case vs Control)
res_infection <- results(dds, contrast = c("infection", "Case", "Control"))
summary(res_infection)

# Subset genes with adjusted p-value < 0.05
de_inf <- res_infection[
  !is.na(res_infection$padj) & res_infection$padj < 0.05,
]

# Number of differentially expressed genes
nrow(de_inf)

# Direction of expression changes
table(de_inf$log2FoldChange > 0)


# optional: Rank genes by adjusted p-value
res_ordered <- res_infection[order(res_infection$padj), ]
res_ordered <- res_ordered[!is.na(res_ordered$padj), ]

top_n <- 10
top_genes <- res_ordered[1:top_n, c("log2FoldChange", "pvalue", "padj")]
top_genes


# optional: Rank significant genes by effect size (absolute log2 fold change)
top_effect_genes <- de_inf[
  order(abs(de_inf$log2FoldChange), decreasing = TRUE),
]

# optional: Inspect genes with largest expression changes
as.data.frame(head(top_effect_genes, 20))


# Genes of interest reported by Singhania et al. (2019)
genes_of_interest <- c(
  "ENSMUSG00000059668",  # Stat1
  "ENSMUSG00000059741",  # Irf7
  "ENSMUSG00000041515"   # Isg15
)

# Confirm genes are present in the results
genes_of_interest[genes_of_interest %in% rownames(res_infection)]

# Effect sizes and significance for selected genes
res_infection[genes_of_interest, c("log2FoldChange", "padj")]


# Extract normalized counts for interpretation
norm_counts <- counts(dds, normalized = TRUE)

norm_counts[genes_of_interest, ]




# 3. Overrepresentation analysis

BiocManager::install(c("clusterProfiler", "org.Mm.eg.db"))

library(clusterProfiler)
library(org.Mm.eg.db)

# Define differentially expressed genes
de_genes <- rownames(res_infection)[
  !is.na(res_infection$padj) & res_infection$padj < 0.05
]

length(de_genes)

# Define background gene set
gene_universe <- rownames(res_infection)

# Perform GO enrichment analysis (Biological Process)
ego_bp <- enrichGO(
  gene          = de_genes,
  universe      = gene_universe,
  OrgDb         = org.Mm.eg.db,
  keyType       = "ENSEMBL",
  ont           = "BP",
  pAdjustMethod = "BH",
  pvalueCutoff  = 0.05,
  qvalueCutoff  = 0.05,
  readable      = TRUE
)

head(ego_bp)

# Save enrichment results
ego_df <- as.data.frame(ego_bp)
write.table(
  ego_df,
  file = "GO_enrichment_BP.tsv",
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)

# Visualize enriched GO terms
png("GO_dotplot_BP.png", width = 900, height = 700)
dotplot(ego_bp, showCategory = 15)
dev.off()

png("GO_barplot_BP.png", width = 900, height = 700)
barplot(ego_bp, showCategory = 15)
dev.off()


